### ISSUE TITLE
repeating rows/SNPs in gwas 

### ISSUE THREAD

**Issue by roxyisat-rex** [MRCIEU/gwas-vcf-specification#10]
Hello 
I am writing because while using the MRCIEU open GWAS project, I came across a GWAS for ALS and on the ieu webpage https://gwas.mrcieu.ac.uk/datasets/ebi-a-GCST005647/ it states that this gwas has around 39 million SNPs. However, when I downloaded and converted to .txt and reformatted using ```unique(sumstats_file)``` in R, there were only about 9 million left. 30 million rows of SNPs got removed! I checked and the rows/SNPs that got removed were duplicates. 
I then went to the webpage provided by the paper and downloaded their sumstats file and it contained about 10 million SNPs, roughly corresponding to the unique 9 million+ from the .VCF. 
This is quite problematic, for all sorts of reasons and especially when multiple comparisons are made. I am quite curious to why this happened. 
On the ieu website, there is no particular issues contact, so I am choosing to report it here. Hopefully it will get answered. Thanks very much.

**Comment by mcgml** [comment]
Hi @roxyisat-rex

Thanks for raising this. The data is a copy of this file ```ftp://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/NicolasA_29566793_GCST005647/harmonised/29566793-GCST005647-EFO_0000253-build37.f.tsv.gz``` (which also contains the duplicated rows). We'll let the GWAS catalog know and update our data.

Thanks
Matt
