### ISSUE TITLE
Convert OR and 95%CI to ES and SE

### ISSUE THREAD

**Issue by vforget** [MRCIEU/gwas-vcf-specification#11]
Hi,

How do you handle harmonizing case/control GWAS where sumstats are reported as OR and 95%CI? Is there established method to convert this to ES and SE?

Thanks,

Vince

**Comment by vforget** [comment]
This comes to mind:

```
z <- -0.862 + sqrt(0.743 - 2.404 * log(p.value))
effect <- log(oddsratio)
SE <- abs(effect/z)
```

Adapted from: https://www.bmj.com/content/343/bmj.d2304.

But this required p-value. There are some GWAS that only report CI.

**Comment by mcgml** [comment]
Hi @vforget 

You can use log odds ratio for ES and corresponding SE

```R
# log odds ratio and 95% CI
lor <- log(or)
lor_lci <- log(or_lci)
lor_uci <- log(or_uci)

# log odds ratio SE
lor_se <- (lor_uci - lor_lci) / 3.92
```
