### ISSUE TITLE
How to perform CAUSE with GWAS-VCF files?

### ISSUE THREAD

**Issue by Hellenzz** [MRCIEU/gwas-vcf-specification#8]
Hi,

I performed two-sample Mendelian randomization analyses for several traits through OpenGWAS database, and now I'm trying the new method CAUSE (Causal Analysis Using Summary Effect Estimates, PMID: 32451458), which needs to format GWAS summary data of exposure and outcome traits first. I have two questions: 

(1) How to extract several specific columns (e.g. beta, se, A1, A2) from the downloaded GWAS-VCF files to a tabular form?
(2) Some of the GWAS-VCF files were not found (e.g. https://gwas.mrcieu.ac.uk/files/finn-a-I9_HYPTENS/finn-a-I9_HYPTENS.vcf.gz), where can I download them?

Many thanks,
Hellen

**Comment by mcgml** [comment]
Hi Hellen

Thanks for the message. You can extract data using bcftools described [here](https://github.com/mrcieu/gwas2vcf#export-to-nhgri-ebi-gwas-catalog-format). 

@explodecomputer are able to help with the missing GWAS-VCF?

Best wishes
Matt

**Comment by Hellenzz** [comment]
Hi Matt, thank you for your prompt reply, bcftools solved my first problem.

Hi @explodecomputer, would you please do me a favor with the missing GWAS-VCF files?
